"""
BLM V3 — Market Event Classifier.

Groups related signals into higher-level market events.  An event represents
a sustained market condition (e.g. a "Trap Formation" that spans multiple
snapshots) rather than a single threshold crossing.

The classifier maintains a lookback window of recent signals and groups them
by temporal proximity and signal type relationships.
"""

from __future__ import annotations

import math
from typing import Any, Optional


# ── Constants ────────────────────────────────────────────────────────

GROUP_WINDOW_SECONDS: float = 15.0
"""Maximum time gap between signals to be grouped into one event."""

MIN_SIGNALS_FOR_EVENT: int = 2
"""Minimum number of related signals required to form an event."""


# ── Event type mappings ──────────────────────────────────────────────

# Maps signal types → resulting event type
SIGNAL_TO_EVENT: dict[str, str] = {
    # Freeze + compression = "market_stall"
    "line_freeze": "market_stall",
    "odds_compression": "market_stall",
    # Jump + expansion = "market_volatility"
    "line_jump": "market_volatility",
    "odds_expansion": "market_volatility",
    # Sharp + fake = "manipulation_attempt"
    "sharp_movement": "manipulation_attempt",
    "fake_movement": "manipulation_attempt",
    # Trap signals = "trap_event"
    "trap_formation": "trap_event",
    "bull_trap": "trap_event",
    "bear_trap": "trap_event",
    # Inflation + overreaction = "overreaction_wave"
    "inflation_spike": "overreaction_wave",
    "overreaction": "overreaction_wave",
    # Correction + regression = "market_reset"
    "market_correction": "market_reset",
    "regression": "market_reset",
    # Momentum + pace = "game_shift"
    "momentum_swing": "game_shift",
    "pace_collapse": "game_shift",
}


def classify_events(
    current_signals: list[dict[str, Any]],
    recent_signals: list[dict[str, Any]],
    current_timestamp: str,
    current_snapshot_id: str,
    game_id: str,
    group_window: float = GROUP_WINDOW_SECONDS,
) -> list[dict[str, Any]]:
    """Group current and recent signals into market events.

    Args:
        current_signals: Signals from the current snapshot.
        recent_signals: Signals from recent snapshots (within lookback window).
        current_timestamp: ISO 8601 timestamp of current snapshot.
        current_snapshot_id: Snapshot ID of current observation.
        game_id: Game identifier.
        group_window: Maximum seconds between signals for grouping.

    Returns:
        List of event dicts ready for insertion into ``market_events`` table.
    """
    if not current_signals and not recent_signals:
        return []

    # Build a pool of candidate signals
    pool = recent_signals + current_signals

    # Group by event category (via SIGNAL_TO_EVENT mapping)
    event_groups: dict[str, list[dict[str, Any]]] = {}
    for sig in pool:
        stype = sig.get("signal_type", "")
        event_type = SIGNAL_TO_EVENT.get(stype)
        if event_type is None:
            continue
        if event_type not in event_groups:
            event_groups[event_type] = []
        event_groups[event_type].append(sig)

    # Build event records
    events: list[dict[str, Any]] = []
    for event_type, sigs in event_groups.items():
        if len(sigs) < MIN_SIGNALS_FOR_EVENT:
            continue

        # Compute event magnitude as max severity × signal count
        max_severity = max(
            _severity_score(s.get("severity", "mid"))
            for s in sigs
        )
        avg_value = sum(
            abs(s.get("value", 0) or 0) for s in sigs
        ) / max(len(sigs), 1)
        magnitude = round(avg_value * (max_severity / 5.0), 2)

        # Build description
        # Deduplicate signal types
        types_fired = list(set(s.get("signal_type", "") for s in sigs))
        description = f"Event: {event_type} — {len(sigs)} signals ({', '.join(types_fired)})"

        events.append({
            "id": "",  # will be generated by models
            "game_id": game_id,
            "snapshot_id": current_snapshot_id,
            "timestamp": current_timestamp,
            "event_type": event_type,
            "duration_seconds": group_window,
            "magnitude": magnitude,
            "description": description,
            "data_json": None,
        })

    return events


def _severity_score(severity: str) -> float:
    """Convert severity string to a numeric score for magnitude calculation."""
    mapping = {"low": 1.0, "mid": 2.0, "high": 4.0, "critical": 5.0}
    return mapping.get(severity, 2.0)
