"""BLM V2 — Alert Models and Manager

Configurable alert rules engine that evaluates game snapshots against
trigger conditions and surfaces actionable alerts to the dashboard.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class AlertSeverity(str, Enum):
    """Severity levels for BLM alerts."""

    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class AlertType(str, Enum):
    """Types of alerts the rules engine can detect."""

    TRAP_METER_HIGH = "trap_meter_high"
    MOMENTUM_REVERSAL = "momentum_reversal"
    CONFIDENCE_DROP = "confidence_drop"
    LARGE_VEGAS_MOVEMENT = "large_vegas_movement"
    LARGE_BLM_MOVEMENT = "large_blm_movement"
    SHARP_MONEY = "sharp_money"
    LATE_TRAP = "late_trap"
    INJURY_DETECTED = "injury_detected"


class Alert(BaseModel):
    """A single BLM alert generated by the rules engine.

    Each alert is uniquely identified, scoped to a game, and carries
    severity, a human-readable title + message, and lifecycle flags.
    """

    id: str = Field(..., description="Unique alert identifier (UUID).")
    game_id: str = Field(..., description="Game this alert belongs to.")
    type: AlertType = Field(..., description="Alert type / trigger rule.")
    severity: AlertSeverity = Field(
        default=AlertSeverity.INFO,
        description="Severity level indicating urgency.",
    )
    title: str = Field(..., description="Short human-readable alert title.")
    message: str = Field(
        ..., description="Detailed human-readable alert message."
    )
    timestamp: datetime = Field(
        default_factory=datetime.now,
        description="ISO 8601 timestamp when the alert was generated.",
    )
    snapshot_data: Optional[dict] = Field(
        default=None,
        description="Snapshot snapshot at the time of alert generation.",
    )
    acknowledged: bool = Field(
        default=False,
        description="Whether the alert has been acknowledged by a user.",
    )
    dismissed: bool = Field(
        default=False,
        description="Whether the alert has been dismissed (hidden from active feed).",
    )

    def to_dict(self) -> dict:
        """Return a JSON-serialisable dict."""
        return {
            "id": self.id,
            "game_id": self.game_id,
            "type": self.type.value,
            "severity": self.severity.value,
            "title": self.title,
            "message": self.message,
            "timestamp": self.timestamp.isoformat(),
            "snapshot_data": self.snapshot_data,
            "acknowledged": self.acknowledged,
            "dismissed": self.dismissed,
        }
